### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by polRk** [Pwntus/change-hairstyle-ai#1]
"Please upgrade your Upload.io account."

**Comment by 1cedsoda** [comment]
Same

**Comment by Lbhateja** [comment]
Same for me.There seems to be issue with uploading the picture

**Comment by Pwntus** [comment]
Thank you for reporting and sorry for this. I've updated the app to not depend on the upload-service. Images will be base64 encoded and included in the Replicate prediction API call.

cc: @polRk @1cedsoda @Lbhateja
