### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by pocketfoundryapps** [Pwntus/change-hairstyle-ai#3]
After loading an image, and no matter what hairstyle is chosen, it gets stuck on the "401 (may take 3 minutes)..."
I've tried both the online one and setting it up locally. Neither works and just keep getting the loading screen constantly. The longest I've waited is 35 mins after which I stopped it. Couldn't find any error messages either.

Any fixes to this?

**Comment by Pwntus** [comment]
I had to disable this in Replicate since it's costing me too much. Sorry about that!

**Comment by pocketfoundryapps** [comment]
That's perfectly fine but how can I go about enabling it with my own payment?
I added in my own Replicate API key, though that didn't change much.

**Comment by Pwntus** [comment]
I'm using a deployment that is only available to me in Replicate. You could create the deployment yourself and change it here https://github.com/Pwntus/change-hairstyle-ai/blob/main/server/api/create.post.ts#L6 or switch to the public model by using the create prediction endpoint here: https://github.com/Pwntus/change-hairstyle-ai/blob/main/server/api/create.post.ts#L9 and adding the `version` property to the JSON payload with the correct model version.

Using a public model the code would look like this:
```js
  // Using public model
  endpoint = "https://api.replicate.com/v1/predictions"

  // Create prediction
  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Token ' + useRuntimeConfig().replicateApiToken
      },
      body: JSON.stringify({
        version: 'b95cb2a16763bea87ed7ed851d5a3ab2f4655e94bcfb871edba029d4814fa587',
        input: {
          image,
          editing_type: 'both',
          hairstyle_description: hairstyle,
          color_description: `${shade} ${color}`
        }
      })
    })
    const json = await response.json()
```
