### ISSUE TITLE
change the code to public model added the token but still the loading screen with "401 (may take 3 minutes)..." is there. what else need to be configured and how i can add the version property to the JSON payload where i can get that

### ISSUE THREAD

**Issue by Shaanalam27** [Pwntus/change-hairstyle-ai#4]
export default defineEventHandler(async (event) => {
  const { image, hairstyle, shade, color } = await readBody(event)

  // Using deployments
  // const endpoint = 'https://api.replicate.com/v1/deployments/replicate/changehairstyleai-com/predictions'

  // Using public model
  const endpoint = 'https://api.replicate.com/v1/predictions'

  // Create prediction
  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'added my token here  ' + useRuntimeConfig().replicateApiToken
      },
      body: JSON.stringify({
        version:
          'b95cb2a16763bea87ed7ed851d5a3ab2f4655e94bcfb871edba029d4814fa587',
        input: {
          image,
          editing_type: 'both',
          hairstyle_description: hairstyle,
          color_description: `${shade} ${color}`
        }
      })
    })
    const json = await response.json()

    // Parse prediction
    const id = json.id
    const status = json.status
    const output = json.output

    return { id, status, output }
  } catch (e) {
    console.log('ERROR', e)
  }
})

**Comment by Pwntus** [comment]
I think this is due to a cold boot.

**Comment by Pwntus** [comment]
I've made an update where you can purchase credits to create hairstyles now, you can still fork this repo and use it yourself if you want.
