### ISSUE TITLE
Regardless of browser, settings or device: can't use changehairstyleai.com?

### ISSUE THREAD

**Issue by siebsieb** [Pwntus/change-hairstyle-ai#7]
Hi there! I'd love to use your creation changehairstyleai. Though, regardless of where I try it, with which settings and with what picture (Safari, Chrome, Android phone, Macbook, etc.) nothing happens after I click 'CREATE HAIRSTYLE'. Nothing changes. What am I missing or can I do to fix this? Thank you!

**Comment by Pwntus** [comment]
Hey @siebsieb Sorry about this - I had to disable it since it was costing me too much.

I've made an update where you can purchase credits to create hairstyles now, you can still fork this repo and use it yourself if you want.
